use database MDB;
use schema PUBLIC;

use schema FFMT;
show file formats;

CREATE OR REPLACE FILE FORMAT CSVT_1
TYPE='CSV'
PARSE_HEADER=TRUE
RECORD_DELIMITER='\n'
FIELD_DELIMITER=','
FIELD_OPTIONALLY_ENCLOSED_BY='"'
ENCODING='UTF8';

describe file format CSVT_1;


Create or replace stage MDB.E_STG.schemaEv
storage_integration = es3
url ='s3://snowflakeff/sourcefolder/'
FILE_FORMAT = (FORMAT_NAME = MDB.FFMT.CSVT_1);

LIST @MDB.E_STG.schemaEv;

--drop file format CSVT_2;

CREATE OR REPLACE FILE  FORMAT MDB.FFMT.CSVT_2
TYPE='CSV'
--PARSE_HEADER=TRUE
--RECORD_DELIMITER='\n'
skip_header = 1
FIELD_DELIMITER=','
FIELD_OPTIONALLY_ENCLOSED_BY='"'
ENCODING='UTF8'
ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE OR REPLACE TABLE MDB.PUBLIC.CUSTOMER_DATA
            USING TEMPLATE (
               SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*)) FROM TABLE(
                    INFER_SCHEMA(
                    LOCATION=>'@MDB.E_STG.source_STAGE/Customer.csv',
                    FILE_FORMAT=>'MDB.FFMT.CSVT_1',
                    IGNORE_CASE=>TRUE) )  );
--TRUNCATE TABLE MDB.PUBLIC.CUSTOMER_DATA;
show tables;
Select * from MDB.PUBLIC.CUSTOMER_DATA;

Alter table MDB.PUBLIC.CUSTOMER_DATA set ENABLE_SCHEMA_EVOLUTION = TRUE;

Alter file format MDB.FFMT.CSVT_1 set ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;
Alter file format MDB.FFMT.CSVT_1 set PARSE_HEADER = TRUE;


SELECT * FROM MDB.PUBLIC.CUSTOMER_DATA;

COPY INTO MDB.PUBLIC.CUSTOMER_DATA
FROM @MDB.E_STG.source_STAGE/Customer.csv
FILE_FORMAT = (
  TYPE = CSV,
  PARSE_HEADER = TRUE,
  FIELD_DELIMITER = ',',
  FIELD_OPTIONALLY_ENCLOSED_BY = '"',
  DATE_FORMAT = 'AUTO',
  COMPRESSION = NONE,
  MULTI_LINE = TRUE,
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;



create or replace file format MDB.FFMT.schemaEvolution_csv
TYPE = CSV
  PARSE_HEADER = TRUE
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  DATE_FORMAT = 'AUTO'
  COMPRESSION = NONE
  MULTI_LINE = TRUE
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

  COPY INTO MDB.PUBLIC.CUSTOMER_DATA
FROM @MDB.E_STG.source_STAGE/Customer.csv
FILE_FORMAT = (FORMAT_NAME = MDB.FFMT.schemaEvolution_csv)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

describe file format MDB.FFMT.CSVT_1;