use database MDB;
use schema PUBLIC;

set query_tag = 'Avr';

--drop table MDB.PUBLIC.LINEITEM_SOS;
--drop table MDB.PUBLIC.LINEITEM_NO_SOS;
CREATE TABLE MDB.PUBLIC.LINEITEM_SOS
AS
SELECT * FROM 
SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM ;

Create table MDB.PUBLIC.LINEITEM_NO_SOS clone MDB.PUBLIC.LINEITEM_SOS;

Show tables;

ALTER TABLE MDB.PUBLIC.LINEITEM_SOS ADD SEARCH OPTIMIZATION ON EQUALITY(L_COMMENT);
ALTER TABLE MDB.PUBLIC.LINEITEM_SOS ADD SEARCH OPTIMIZATION ON EQUALITY(l_orderkey);

Show tables;

select * from MDB.PUBLIC.lINEITEM_SOS where L_orderkey = '4509487233';
select * from MDB.PUBLIC.lINEITEM_SOS where l_COMMENT = 'GOOD PRODUCTS';


select * from MDB.PUBLIC.lINEITEM_NO_SOS where L_orderkey = '4509487233';
select * from MDB.PUBLIC.lINEITEM_NO_SOS where L_COMMENT = 'GOOD PRODUCTS';

SELECT SYSTEM$ESTIMATE_SEARCH_OPTIMIZATION_COSTS('MDB.PUBLIC.LINEITEM_SOS') AS SOS_ESTIMATE;