USE DATABASE MDB;
USE SCHEMA PUBLIC;
CREATE OR REPLACE TABLE PUBLIC.CUSTOMER_NONCLUSTER (
	C_CUSTKEY NUMBER(38,0),
	C_NAME VARCHAR(25),
	C_ADDRESS VARCHAR(40),
	C_NATIONKEY NUMBER(38,0),
	C_PHONE VARCHAR(15),
	C_ACCTBAL NUMBER(12,2),
	C_MKTSEGMENT VARCHAR(10),
	C_COMMENT VARCHAR(117)
);

CREATE OR REPLACE TABLE PUBLIC.CUSTOMER_CLUSTER (
	C_CUSTKEY NUMBER(38,0),
	C_NAME VARCHAR(25),
	C_ADDRESS VARCHAR(40),
	C_NATIONKEY NUMBER(38,0),
	C_PHONE VARCHAR(15),
	C_ACCTBAL NUMBER(12,2),
	C_MKTSEGMENT VARCHAR(10),
	C_COMMENT VARCHAR(117)
)
CLUSTER BY (C_NATIONKEY);

use database MDB;

show tables;

INSERT INTO CUSTOMER_CLUSTER SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER;

INSERT INTO CUSTOMER_NONCLUSTER SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER;

SELECT COUNT(*) from CUSTOMER_NONCLUSTER;
SELECT COUNT(*) FROM CUSTOMER_CLUSTER;  

SELECT * FROM PUBLIC.CUSTOMER_NONCLUSTER WHERE C_NATIONKEY=2; --  15 sec -- 420/420 mp scanned

SELECT * FROM PUBLIC.CUSTOMER_CLUSTER WHERE C_NATIONKEY=2;

CREATE OR REPLACE TABLE PUBLIC.ORDERS_NONCLUSTER AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS;

CREATE OR REPLACE TABLE PUBLIC.ORDERS_CLUSTER AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS;

ALTER TABLE PUBLIC.ORDERS_CLUSTER CLUSTER BY(YEAR(O_ORDERDATE));

ALTER TABLE PUBLIC.ORDERS_CLUSTER CLUSTER BY(YEAR(O_ORDERDATE),O_ORDERPRIORITY);

Select SYSTEM$CLUSTERING_INFORMATION('ORDERS_CLUSTER');

--SET RESULT_CACHE = FALSE
--ALTER SESSION SET USE_CACHED_RESULT = FALSE;
ALTER SESSION SET USE_CACHED_RESULT = TRUE;

-- Stop Snowflake from auto-clustering (saves cost)
ALTER TABLE PUBLIC.ORDERS_CLUSTER SUSPEND RECLUSTER;
Alter table PUBLIC.ORDERS_CLUSTER resume recluster;