-- I ahve created a Account with in the accounr itself
https://foaxzgc-blc70336avb.snowflakecomputing.com
venkat1 :: UserName
dgE7wFatNYceTmNDstuc :: PASS

--PROVIDER 
----------------------------------------------------------------------
use warehouse compute_wh;

CREATE DATABASE CUST_DB;

Create or replace schema SO;
use schema SO;
create or replace share CUST_DATA_SHARE;
show shares;
--Grant access to Share CUST_DATA_SHARE on warehouse
GRANT USAGE ON warehouse compute_wh TO ROLE  SYSADMIN;
--Grant access to Share CUST_DATA_SHARE on Database
GRANT USAGE ON DATABASE CUST_DB TO SHARE CUST_DATA_SHARE;


// Create schemas
CREATE SCHEMA CUST_TBLS;
CREATE SCHEMA CUST_VIEWS;

use DATABASE CUST_DB;

CREATE TABLE CUST_DB.CUST_TBLS.CUSTOMER
AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

CREATE TABLE CUST_DB.CUST_TBLS.ORDERS
AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;

GRANT USAGE ON SCHEMA CUST_TBLS TO SHARE CUST_DATA_SHARE;
GRANT SELECT ON TABLE CUST_DB.CUST_TBLS.CUSTOMER TO SHARE CUST_DATA_SHARE;
GRANT SELECT ON TABLE CUST_DB.CUST_TBLS.ORDERS TO SHARE CUST_DATA_SHARE;

--Create a view in views schema
CREATE OR REPLACE VIEW CUST_VIEWS.VW_CUST
AS
SELECT CST.C_CUSTKEY, CST.C_NAME, CST.C_ADDRESS, CST.C_PHONE FROM 
SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER CST
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION NTN
ON CST.C_NATIONKEY = NTN.N_NATIONKEY
WHERE NTN.N_NAME='BRAZIL';

-- Create a secure view in views schema
CREATE OR REPLACE SECURE VIEW CUST_VIEWS.SEC_VW_CUST
AS
SELECT CST.C_CUSTKEY, C_NAME,C_ADDRESS, C_PHONE 
FROM CUST_DB.CUST_TBLS.CUSTOMER CST;

Show views in DATABASE CUST_DB;
--Create a  mat view in views schema
CREATE MATERIALIZED VIEW CUST_DB.CUST_VIEWS.MAT_VW_ORDERS
AS
SELECT * FROM CUST_DB.CUST_TBLS.CUSTOMER;

--Create a secure mat view in views schema
CREATE SECURE MATERIALIZED VIEW CUST_DB.CUST_VIEWS.SEC_MAT_VW_ORDERS
AS
SELECT * FROM CUST_DB.CUST_TBLS.CUSTOMER;

SELECT CURRENT_SCHEMA();

GRANT USAGE ON SCHEMA CUST_VIEWS TO SHARE CUST_DATA_SHARE;
GRANT SELECT ON VIEW CUST_DB.CUST_VIEWS.VW_CUST TO SHARE CUST_DATA_SHARE; --Non-secure object can only be granted to shares with "secure_objects_only" property set to false.
GRANT SELECT ON VIEW CUST_DB.CUST_VIEWS.SEC_VW_CUST TO SHARE CUST_DATA_SHARE; -- SHARE SUCCESS
GRANT SELECT ON VIEW CUST_DB.CUST_VIEWS.MAT_VW_ORDERS TO SHARE CUST_DATA_SHARE; --Non-secure object can only be granted to shares with "secure_objects_only" property set to false.
GRANT SELECT ON VIEW CUST_DB.CUST_VIEWS.SEC_MAT_VW_ORDERS TO SHARE CUST_DATA_SHARE;-- SHARE SUCCESS

SHOW GRANTS TO SHARE CUST_DATA_SHARE;

--Add the consumer account to share the data
ALTER SHARE CUST_DATA_SHARE ADD ACCOUNT = QYC91436;


--CONSUMER
---------------------------------------------------------------------------------------
--USE ROLE ACCOUNTADMIN

SHOW SHARES;

DESC SHARE CUST_DATA_SHARE; --SQL compilation error: Share '"QYC91436.CUST_DATA_SHARE"' does not exist or not authorized.

CREATE DATABASE CUST_DATA_SHARE_DB FROM SHARE FOAXZGC.BLC70336.CUST_DATA_SHARE;

USE DATABASE CUST_DATA_SHARE_DB;

SHOW TABLES;

SHOW VIEWS IN SCHEMA CUST_VIEWS;

----------------------------------------------------------------------------------------------------

--NOW WE ARE SHARING THE DATA WITH NON-SNOWFLKAE USERS USING READER OBJECT ONLY
CREATE MANAGED ACCOUNT CUSTOMER_ANALYST
ADMIN_NAME = cust_analyst,
ADMIN_PASSWORD = 'tA8pmzL4fRjAZPF',
TYPE = READER;

SHOW MANAGED ACCOUNTS;

ALTER SHARE CUST_DATA_SHARE ADD ACCOUNT = BPC85048
SHARE_RESTRICTIONS = FALSE;

SHOW SHARES;

CREATE DATABASE CUST_DATA_SHARE_DB FROM SHARE FOAXZGC.BLC70336.CUST_DATA_SHARE;

SHOW TABLES;

SHOW VIEWS IN SCHEMA CUST_VIEWS;





